name: Docker Compose build

on:
  pull_request:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      compose: ${{ steps.filter.outputs.compose }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          token: ""
          filters: |
            compose:
              - "compose.yaml"

  compose:
    runs-on: ubuntu-latest
    needs:
      - changes
    if: needs.changes.outputs.compose == 'true'
    steps:
      - uses: actions/checkout@v4
      - run: docker compose config --quiet
      - run: docker compose pull --dry-run
