name: Docker Compose build

on:
  pull_request:

jobs:
  changes:
    runs-on: ubuntu-slim
    outputs:
      compose: ${{ steps.filter.outputs.compose }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        id: filter
        with:
          token: ""
          filters: |
            compose:
              - "compose.yaml"

  compose:
    runs-on: ubuntu-latest
    needs:
      - changes
    if: needs.changes.outputs.compose == 'true'
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - run: docker compose config --quiet
      - run: docker compose pull --dry-run
